#!/usr/bin/env bash
# This bash script installs and configures nginx

# Update the package index and install nginx
sudo apt-get update
sudo apt-get install nginx -y

# content of the html webpage
echo 'Hello World!' > /var/www/index.html

# start nginx
sudo /etc/init.d/nginx start
