#!/usr/bin/env bash
# This bash script installs and configures nginx

# Update the package index and install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure nginx to listen on port 80 and serve the Hello World! message
sudo echo "server {
    listen 80 default_server;
    server_name 52.87.219.225;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
sudo /etc/init.d/nginx restart
