#!/usr/bin/env bash
# Configure Nginx to add a custom HTTP response header

sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y

sudo sed -i "0,/server {/s//server {\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-available/default

sudo service nginx restart
