#!/usr/bin/env bash
# Configure Nginx to add a custom HTTP response header

sudo sed -i "/server {/a \	add_header X-Served-By \$HOSTNMAE;" /etc/nginx/sites-available/default"

sudo service nginx restart
