#!/usr/bin/env bash
# Bash script that configures HAproxy as a load balancer

# installing dependencies and packages
sudo apt-get update -y
sudo apt-get -y install haproxy

# configuring the Haproxy configuration file
CONFIG=$(cat <<EOF
frontend myfrontend
        bind *:80
        default_backend myservers

backend myservers
        balance roundrobin
        server 174890-web-01 52.87.219.225:80 check
	server 174890-web-02 54.160.96.18:80 check
EOF
)

echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg

echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# restart haproxy server
sudo service haproxy restart
