#!/usr/bin/env bash
# Debugging web server to listen on port 80

# Edit the configuration file to listen on port 80
sudo sed -i 's/ipv6only=on//' /etc/nginx/sites-available/default

sudo service nginx restart
