#!/usr/bin/env bash
# Debugging web server to listen on port 80
sudo sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default

sudo rm /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
