#!/usr/bin/env bash
# Debugging web server to listen on port 80

sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Back up the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Edit the configuration file to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Check the syntax of the configuration file
sudo nginx -t

if [ $? -eq 0 ]; then
  # Reload the Nginx configuration
  sudo ln -s /etc/nginx/sites-available/default /etc/nginx/site-available/default
  sudo service nginx restart
else
  # Restore the original configuration file
  sudo cp /etc/nginx/sites-available/default.bak /etc/nginx/sites-available/default
  echo "Error: the new configuration file is invalid, the original configuration file has been restored."
fi
