#!/usr/bin/env bash
# This script creates an RSA key pair
# key stored in 'school' with 4096 bits and passprhase of 'betty'

# Name of file to save the key pair with
FILE='school'

# variable that holds the passprhase
PASSPHRASE='betty'

# size of the key pair bits
KEY_SIZE=4096

# the actual script
ssh-keygen -t rsa -b $KEY_SIZE -f $FILE -N "$PASSPHRASE"
